version: '3.1'

services:
  app:
    image: guillaumedorschner/hackme:latest
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
    environment:
      PASSWORD_DATABASE: "your_password"
      HOST_DATABASE: db  
      PORT_DATABASE: "5432"
      USER_DATABASE: "your_user"
      DATABASE: "your_database"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "your_database"
      POSTGRES_USER: "your_user"
      POSTGRES_PASSWORD: "your_password"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
